### ISSUE TITLE
Failed pinning files to ipfs

### ISSUE THREAD

**Issue by ztnark** [decentraland/cli#123]
dcl link ends in "Failed pinning files to ipfs"

IPFS daemon running on Windows.

Here is the tx: https://etherscan.io/tx/0xb9c9a78bcba221b2c48d9cc34e9f97881a87bc730c1184352511b4279a150b05

**Comment by menduz** [comment]
@nachomazzara

**Comment by nachomazzara** [comment]
@ztnark, so far we check against **Ropsten** when trying to pin files to IPFS. We will let you know when pinning works with mainnet

**Comment by eordano** [comment]
Fixed on current IPFS server and cli version (master). Please await for the next release

**Comment by ztnark** [comment]
After updating, now I receive:

```Uploading project to IPFS:
Error trying to connect Ethereum wallet: Invalid JSON RPC response: ""
Uploading 1/2 files to IPFS (262144 bytes uploaded)
Uploading 2/2 files to IPFS (287394 bytes uploaded)
Successfully added files to local IPFS node
Uploading 3/2 files to IPFS (533 bytes uploaded)
Unable to get LANDRegistry contract instance
```

**Comment by nachomazzara** [comment]
@ztnark hey! sorry for that, which version are you using? 

Yesterday, we deployed a new version fixing that. Could you please install @latest?

**Comment by ztnark** [comment]
I've just updated to 1.0.2, created a new project, and I'm still receiving the same error.

**Comment by nachomazzara** [comment]
Reference to #150
