### ISSUE TITLE
ReplaceWholeTreeException when calling Rendering a ScriptableScene

### ISSUE THREAD

**Issue by lylepratt** [decentraland/cli#170]
I'm working on a multiplayer scene. I receive the following error when I call `updateAll()` on the `ConnectedClients`

```
{ Error: ReplaceWholeTreeException
    at d.render (http://localhost:2044/metaverse-api/preview.js:19:60355)
    at g.processMessage (http://localhost:2044/metaverse-api/preview.js:12:202779)
    at transport.onMessage.e (http://localhost:2044/metaverse-api/preview.js:12:204357)
    at WebSocket.e.addEventListener.e (http://localhost:2044/metaverse-api/preview.js:12:199167)
  code: -32603,
  data: 
   { name: 'Error',
     message: 'ReplaceWholeTreeException',
     stack: 'Error: ReplaceWholeTreeException\n    at d.render (http://localhost:2044/metaverse-api/preview.js:19:60355)\n    at g.processMessage (http://localhost:2044/metaverse-api/preview.js:12:202779)\n    at transport.onMessage.e (http://localhost:2044/metaverse-api/preview.js:12:204357)\n    at WebSocket.e.addEventListener.e (http://localhost:2044/metaverse-api/preview.js:12:199167)' },
  name: 'Error' }
```

I'm not doing anything complex. I'm just generating entities on the fly, looping through them, and added them to be rendered.

In my render() function:
```
    return (
      <scene position={{ x: 1, y: 0, z: 1 }}>
      {componentList}
      </scene>
    );
```
`componentList` is just a list of box elements.

When I call `updateAll()` on connectedClients it works the first time. Then the second time it results in the error I posted above.

**Comment by menduz** [comment]
what is in componentList?

Can you please put a `console.log(JSON.stringify(componentList))` before the `return (` line and share it with us?

**Comment by lylepratt** [comment]
@menduz Sure! I'm basically just iterating over a JSON array of block coordinates and drawing blocks.

```
    var componentList = [];
    for(const block in getState().blocks) {
        const coords = block.split(",");
        const placement = {
          x: parseInt(coords[0]) / 10,
          y: parseInt(coords[1]) / 10,
          z: parseInt(coords[2]) / 10
        };
        componentList.push(
            <box              
              position={placement}
              scale={{ x: .1, y: .1, z: .1 }}
              color={getState().blocks[block].color}
            />
        )
    }
```

Here is the `JSON.stringify` of the `componentList`:
```
[{"tag":"box","attrs":{"position":{"x":0.1,"y":0.1,"z":0.1},"scale":{"x":0.1,"y":0.1,"z":0.1},"color":"red"},"children":[]},{"tag":"box","attrs":{"position":{"x":0.9,"y":0.9,"z":1.1},"scale":{"x":0.1,"y":0.1,"z":0.1},"color":"#612386"},"children":[]},{"tag":"box","attrs":{"position":{"x":0.3,"y":0.6,"z":0.7},"scale":{"x":0.1,"y":0.1,"z":0.1},"color":"#97ce80"},"children":[]},{"tag":"box","attrs":{"position":{"x":1.5,"y":1.7,"z":1.4},"scale":{"x":0.1,"y":0.1,"z":0.1},"color":"#fc178c"},"children":[]}]
```

**Comment by lylepratt** [comment]
I'm hoping to make some more progress on this this weekend. Any tips on my error?

**Comment by m3mnoch** [comment]
hey lyle.  here's sort of a questionable prototype i've been playing with a lot lately.  it may help unlock some of your questions.

just init a new dynamic scene, and use this as your `scene.tsx` file.

```import { createElement, ISimplifiedNode, ScriptableScene, WebWorkerTransport } from "metaverse-api";

export interface IEntity {
  update(deltaTime: number): void;
  render(): ISimplifiedNode;
}

export class SpawnedEntity implements IEntity {
  position = { x: 5, y: 2, z: 5 };
  direction = {
    x: Math.random() * 2 - 1,
    y: Math.random() * 2 + 0.5,
    z: Math.random() * 2 - 1
  };
  lastTime = performance.now();
  boundaryRadius: number = 2;

  speed = 0.0005;

  update(frameTime: number): void {
    const deltaTime = frameTime - this.lastTime;
    this.position.x += this.direction.x * deltaTime * this.speed;
    this.position.y += this.direction.y * deltaTime * this.speed;
    this.position.z += this.direction.z * deltaTime * this.speed;

    if (this.position.x > this.boundaryRadius) this.direction.x *= -1;
    if (this.position.y > this.boundaryRadius) this.direction.y *= -1;
    if (this.position.z > this.boundaryRadius) this.direction.z *= -1;

    if (this.position.x <= -this.boundaryRadius) this.direction.x *= -1;
    if (this.position.y <= -this.boundaryRadius) this.direction.y *= -1;
    if (this.position.z <= -this.boundaryRadius) this.direction.z *= -1;

    // you could tie this entity to a physics system or similar here

    this.lastTime = frameTime;
  }

  render(): ISimplifiedNode {
    return (
      <entity position={{ x: 5, y: 2, z: 5 }}>
        <box
          id="spawnedEntity"
          position={this.position}
          transition={{
            position: { duration: 33 },
            rotation: { duration: 33 }
          }}
          color="#B0C4DE"
        />
      </entity>
    );
  }
}

export class Game extends ScriptableScene<any, { time: number }> {
  state = { time: 0 };
  spawnedEntities: IEntity[] = [];

  renderSpawnedEntities() {
    return this.spawnedEntities.map($ => $.render());
  }
  updateSpawnedEntities() {
    var frameTime: number = performance.now();
    this.spawnedEntities.map($ => $.update(frameTime));
  }

  async sceneDidMount() {
    setTimeout(function() {
      // delaying the spawn.
      const spawnedEntity: SpawnedEntity = new SpawnedEntity();
      theGame.spawnedEntities.push(spawnedEntity);
    }, 2000);

    // let's do the animation update loop.
    const timer = setInterval(() => {
      // run the ai update
      theGame.updateSpawnedEntities();

      // triggering diff/patch the silly way.
      theGame.setState({
        time: performance.now()
      });
    }, 1000 / 16);
  }
  async render() {
    return <scene>{this.renderSpawnedEntities()}</scene>;
  }
}

export const theGame: Game = new Game(WebWorkerTransport(self as any));
```

**Comment by lylepratt** [comment]
Cool! Will give it a shot and report back. Thanks @m3mnoch

**Comment by lylepratt** [comment]
@m3mnoch Unfortunately, the same problem occurs when I use your render methodology.

For others: @menduz told me in Discord that this is "related to a known and fixed bug in the version we are about to release of the SDK". I'll wait for that update and try again.

**Comment by menduz** [comment]
@lylepratt 

You can start trying it out!

```bash
# uninstall the current version of the CLI
npm rm -g decentraland 
# install the preview version of the CLI
npm i -g decentraland@rc
# then in your scene install the next version of metaverse-api
npm i --save-dev metaverse-api@next
```

https://docs.decentraland.today/releases/SDK-4.0.0/

**Comment by lylepratt** [comment]
OK @menduz , Just updated. Getting the same error unfortunately.  :(

**Comment by lylepratt** [comment]
Here is a gif of my problem:
https://www.dropbox.com/s/kkhuckjg79ockg8/decentraland-issue.gif

1) I load the scene and run a command to spawn a block entity. The first command works, and I see the new block.
2) I try to spawn a second command and you can see it fails with the `ReplaceWholeTreeException` issue.
3) I refresh the DLC Preview page, and run the command to spawn another block. It works again (after reloading).
4) I try to spawn another block and it fails with the same `ReplaceWholeTreeException` issue.

The basis for my code is the `08-multiuser-EXPERIMENTAL` scene you guys put out.

**Comment by menduz** [comment]
@lylepratt 

You can start trying it out!

```bash
# uninstall the current version of the CLI
npm rm -g decentraland 
# install the preview version of the CLI
npm i -g decentraland@rc
# then in your scene install the next version of metaverse-api
npm i --save-dev metaverse-api@next
```

https://docs.decentraland.today/releases/SDK-4.0.0/

**Comment by lylepratt** [comment]
Hi Folks, any new insight here?

**Comment by menduz** [comment]
we released a new version of the SDK please follow the following steps to try it out

```bash
# uninstall the current version of the CLI
npm rm -g decentraland
# install the preview version of the CLI
npm i -g decentraland@latest
# then in your scene install the next version of metaverse-api, the CLI will tell you there is a new version anyway
npm i --save-dev metaverse-api@latest
```

And here are the updated release notes https://docs.decentraland.org/releases/sdk/4.0.0/

**Comment by lylepratt** [comment]
@menduz is this a different update from the one you told me about previously? I already tried that one.

**Comment by lylepratt** [comment]
I just followed your instructions and still receive the same error:
```
{ Error: ReplaceWholeTreeException
    at d.render (http://127.0.0.1:8000/metaverse-api/preview.js:19:60355)
    at g.processMessage (http://127.0.0.1:8000/metaverse-api/preview.js:12:202779)
    at transport.onMessage.e (http://127.0.0.1:8000/metaverse-api/preview.js:12:204357)
    at WebSocket.e.addEventListener.e (http://127.0.0.1:8000/metaverse-api/preview.js:12:199167)
  code: -32603,
  data: 
   { name: 'Error',
     message: 'ReplaceWholeTreeException',
     stack: 'Error: ReplaceWholeTreeException\n    at d.render (http://127.0.0.1:8000/metaverse-api/preview.js:19:60355)\n    at g.processMessage (http://127.0.0.1:8000/metaverse-api/preview.js:12:202779)\n    at transport.onMessage.e (http://127.0.0.1:8000/metaverse-api/preview.js:12:204357)\n    at WebSocket.e.addEventListener.e (http://127.0.0.1:8000/metaverse-api/preview.js:12:199167)' },
  name: 'Error' }

```

**Comment by menduz** [comment]
Can you privately share your scene with us so we can debug it and fix the
error?

**Comment by lylepratt** [comment]
@menduz sure. Do you have a bitbucket user I can share it to? The repo is currently at BitBucket.

**Comment by lylepratt** [comment]
@menduz I pushed the code here (public):
https://github.com/lylepratt/decentraland-example

Start the scene:
`dcl preview`

Build the server-side code:
`npm run build`

Run the server-side code:
`npm start`

Open your browser and hit the simple API to add a block to the scene. It should error the 2nd or 3rd time you hit this URL to spawn a block:
http://localhost:8087/block/set?coord=random&color=random

**Comment by lylepratt** [comment]
Any updates here? I'd like to try to get some work done on this over the weekend if possible. :)

**Comment by lylepratt** [comment]
Has anyone had a chance to take a look at the repo I shared above? I'm still having trouble with this issue.

**Comment by lylepratt** [comment]
I tried reinstalling the SDK from scratch and the problem is now resolved as @menduz said it would be. Closing this issue. Thanks for the help!
