### ISSUE TITLE
'dcl info' has stopped working, throws an error

### ISSUE THREAD

**Issue by cfravel** [decentraland/cli#533]
This is hindering district management of tenants.

**Comment by nchamo** [comment]
Hey @cfravel !

We just released a new `@next` version, that you can install by doing:
```npm install -g decentraland@next```

Could you confirm that the fix works for you? If it does, then we can release it as a new version

**Comment by cfravel** [comment]
I've examined this for 73,92.  This is land in Aetheria whose UpdateManager, UpdateOperator and LandUpdateOperator have all been set.
I've also examined it for 14,100 in the Conference Center

DCL INFO is now partially fixed:
1. It doesn't throw an error
2. In both the LAND and ESTATE sections it gets Owner right (including the Passthrough contract, e.g. for Aetheria that is 0x494b9f97c63dfc8c6e6a4298a114e82a2e28e895
3. In the LAND section It gets UpdateOperator right. For 73,92 this is correctly x4959f54f7b30224047ac3cae6bf147bbaee8b61c 
4. In the ESTATE section it gets the UpdateOperator right.   For all of the Aetheria estate, this is 0x98b39480da71e6355f704d67d36f443085af1d8f and for all of the Conference Center this is 0xaf293617a79cCC47958aB781e62fc8c886C8536c
5. It now does show information for 151,151, which is one of the parcels of the Aetheria estate that lies ouside of 150,150 and does have the Estate UpdateOperator set and shown properly

Not correct or missing.
6. It doesn't report anything for Operator in either LAND or ESTATE sections.  I don't know what field this is supposed to be, but it is blank in both sections
7. It doesn't display an important ESTATE field: UpdateManager (that should show as an Ethereum contract address for Aetheria, and for 14,100 in the Conference Center the UpdateManager should show as 0x9609d68eAB639349e6E9a2eec76839ec8d109C22
8. The parcels listed used to be all the parcels in the estate.  Now it is some random list of parcels.

6 and 7 are not new issues, i believe, but 7 would be important to fix for estate management.
8. Is a new breakage with this @next version, and should be fixed asap, hopefully before deployment to latest

**Comment by cfravel** [comment]
Yikes, another case that is still broken

9. dcl info still throws an error if you run it on a parcel that isn't in an estate and doesn' have a scene deployed (e.g. -1,144)

**Comment by nchamo** [comment]
Reopening to continue working on the fixes

@cfravel , could you provide an example for 8 (where the parcels looks random), and specify what the list of parcels should be

**Comment by cfravel** [comment]
Nico Chamo asked for what the parcel list should look like.
First, if the parcel isn't in an estate, the entire ESTATE section is absent, and that is correct.  (except, see #9 above)

If the parcel IS in an estate, the list of parcels is wildly incorrect.
For example:
for any parcel in Aetheria, such as 73,92 the parcel list should have 10,005 items in it, and run the range from X=62 to X=163 and Y=59 to Y-158.
Instead is shows these parcels:

parcels: "62,74; 62,75; 62,76; 62,77; 62,78; 62,79; 62,80; 62,81; 62,82; 62,83; 62,84; 62,85; 62,86; 62,87; 62,88; 62,89; 62,90; 62,91; 62,92; 62,93; 62,94; 62,95; 62,96; 62,97; 62,98; 62,99; 62,100; 62,101; 62,102; 62,103; 62,104; 62,105; 62,106; 62,107; 62,108; 62,109; 62,110; 62,111; 62,112; 62,113; 62,114; 62,115; 62,116; 62,117; 62,118; 62,119; 62,120; 62,121; 62,122; 62,123; 62,124; 62,125; 62,126; 62,127; 62,128; 62,129; 62,130; 62,131; 62,132; 62,133; 62,134; 62,135; 62,136; 62,137; 62,138; 62,139; 62,140; 62,141; 62,142; 62,143; 62,144; 62,145; 62,146; 62,147; 62,148; 62,149; 62,150; 62,151; 62,152; 62,153; 62,154; 62,155; 62,156; 62,157; 62,158; 63,74; 63,75; 63,76; 63,77; 63,78; 63,79; 63,80; 63,81; 63,82; 63,83; 63,84; 63,85; 63,86; 63,87; 63,88"

**Comment by cfravel** [comment]
similarly, for the Conference Center district, if i do dcl info on 14,100, it should give parcels of X from 1 to 33 and Y from 95 to 119 (minus some)
instead it only gives:

parcels: "16,95; 16,96; 16,97; 16,98; 16,99; 16,100; 16,101; 16,102; 16,103; 16,104; 16,105; 16,106; 16,107; 16,108; 16,109; 16,110; 16,111; 16,112; 16,113; 16,114; 16,115; 16,116; 16,117; 16,118; 1,95; 1,96; 1,97; 1,98; 1,99; 1,100; 1,101; 1,102; 1,103; 1,104; 1,105; 1,106; 1,107; 1,108; 1,109; 1,110; 1,111; 1,112; 1,113; 1,114; 1,115; 1,116; 1,117; 1,118; 17,95; 17,96; 17,97; 17,98; 17,99; 17,100; 17,101; 17,102; 17,103; 17,104; 17,105; 17,106; 17,107; 17,108; 17,109; 17,110; 17,111; 17,112; 17,113; 17,114; 17,115; 17,116; 17,117; 17,118; 18,95; 18,96; 18,97; 18,98; 18,99; 18,100; 18,101; 18,102; 18,103; 18,104; 18,105; 18,106; 18,107; 18,108; 18,109; 18,110; 18,111; 18,112; 18,113; 18,114; 18,115; 18,116; 18,117; 18,118; 19,95; 19,96; 19,97; 19,98"

**Comment by cfravel** [comment]
looks like it is only returning some 100 of the total number of parcels.  Both of these districts are larger than 100 parcels

**Comment by nchamo** [comment]
Hey @cfravel !

I'll try to address the comments for each point:
(1) to (5): I'm glad it worked for you!
(6): `operator` is a role assigned to a token (land or estate) that gives a co-ownership to the person assigned to it. They could sell/transfer ownership without the actual owner being involved. Most people don't provide that role, and that's why you see it as blank
(7): The `updateManager` is tricky, so I'll try to explain it just in case someones reads this thread and doesn't understand what it means. `updateManager` is like giving  someone`updateOperator` to all your land/estates. But this is assigned at the address level, so you don't have to update it when you buy or sell a new land/estate. That's why it's not shown as the estates information, it's because it's related to the address. Maybe it should be shown when requesting the information of an address?
(8): As you said, there was a 100 limit. thegraph has a default limit, so the response was being truncated. I'm working around it
(9): Good catch! I'll fix that

**Comment by nchamo** [comment]
Hey @cfravel !

We just released a new `@next` version. Could you check if (8) and (9) were fixed for you?

**Comment by cfravel** [comment]
8) Fixed.   It gives the full 10,005 parcels in the Aetheria district estate when run on 73,92dcl info
9) Fixed.   It gives the corect info for -1,144   there is an owner, but no scene, no estate.

i am a little unsure about your explanation of the estate-level UpdateManager.
For example, in Aetheria, we have assigned the UpdateManager to a smart contract which is used by the self-service dApp we created for privately-allocated plot operators to be able to assign their wallet to LandUpdateOperator roll for specific parcels (as known in our allocation database).    In the Conference Center I created both an UpdateManager and UpdateOperator at the estate level.  The UpdateManager has the ability to assign tenants' wallets to be Land UpdateOperators.  (EstateUpdateOparator doesn't).  I use the estate UpdateOperator to deploy scenes, but the UpdateManager can do that, too.   These were both created through calls to the estate proxy contract.  So it has always felt and read to me that both of these wallets are assigned at the estate level, but just have different powers.   Can you double check?   In any case `dcl info` should be able to display the UpdateManager, and it would be good for a district operator to be able to see all the wallets which are operational in the district,

This is a guide that I wrote for District Managers a year or more ago, and many have used it.   I gathered the information from Esteban, and my understanding from that and when writing and using it is that both UpdateManager and UpdateOperator are assigned and operate through the estate contract.
https://docs.google.com/document/d/1KJN2gkpvRZZZduL--MESO1NwGBYnkiYouH2z4uRb9HU/edit

**Comment by nchamo** [comment]
I'm glad (8) and (9) were fixed for you.

Regarding the `UpdateManager`, I'll let @nicosantangelo and @nachomazzara confirm if it is associated at the address level, or estate level. Maybe they can shine some light on how this works, since you were able to assign them through calls to the estate proxy contract

Regarding (7) itself, let's try to split the fix for the features that stopped working, and the new feature request. Since we are now back to how the cli worked before all the errors, I'll close this issue and release a new `@latest`, so no-one else has to deal with the errors. So Carl, please feel free to create a new issue specifically for (7), so it can be tracked and prioritized accordingly

**Comment by nachomazzara** [comment]
`updateManager` is address level

**Comment by nchamo** [comment]
Looks like this is broken again, reported by @cfravel 

To reproduce run `dcl info 70,75`

**Comment by cfravel** [comment]
Is broken again.
I've tried it in cli 3.4.7, latest and next , they are all broken.
You can see this if you use
dcl info 70,75

**Comment by cfravel** [comment]
retested tonight in 3.5.1 and it worked
hmm.
